# Generated by Django 5.2.1 on 2025-08-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
