# Generated by Django 5.2.1 on 2025-08-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_username', models.CharField(max_length=50)),
                ('owner_username', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(to='registration.usercontact'),
        ),
    ]
