# Generated by Django 5.2.1 on 2025-08-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_usercontact_user_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(blank=True, null=True, to='registration.usercontact'),
        ),
    ]
